[meta]
title = "FastAPI Live Text-to-Speech Starter"
description = "Get started using Deepgram's Live TTS with this FastAPI demo app"
author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
repository = "https://github.com/deepgram-starters/fastapi-live-text-to-speech"
useCase = "Live TTS"
language = "Python"
framework = "FastAPI"

[build]
command = "make init"

[dev]
command = "make dev"
